const { userManager } = require("./userManager");
const { systemSettingManager } = require("./systemSettingManager");

exports.userManager = userManager;
exports.systemSettingManager = systemSettingManager;
exports.users = require("./schema").users;
exports.systemSettings = require("./schema").systemSettings;
exports.qaDatabase = require("./schema").qaDatabase;
exports.robots = require("./schema").robots;
exports.callbackHistory = require("./schema").callbackHistory;
exports.insertUserSchema = require("./schema").insertUserSchema;
exports.updateUserSchema = require("./schema").updateUserSchema;
exports.insertSystemSettingSchema = require("./schema").insertSystemSettingSchema;
exports.updateSystemSettingSchema = require("./schema").updateSystemSettingSchema;
exports.insertQADatabaseSchema = require("./schema").insertQADatabaseSchema;
exports.updateQADatabaseSchema = require("./schema").updateQADatabaseSchema;
exports.insertRobotSchema = require("./schema").insertRobotSchema;
exports.updateRobotSchema = require("./schema").updateRobotSchema;
exports.insertCallbackHistorySchema = require("./schema").insertCallbackHistorySchema;
